name: 'Update data'

on:
  schedule:
    # Run at 12:00 on the 1st of every month.
    - cron: '00 12 1 * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Update data
        run: |
          npm run build
          git config user.name 'Mathias Bynens'
          git config user.email 'mathias@qiwi.be'
          # Update frag data.
          date=$(date +'%Y-%m-%d')
          git add data
          git commit data -m "Add frag data for date=${date}" || true
          git push
